name: Review By LLM

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**'
    branches:
      - main

jobs:
  review-code:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - name: Setup repository
        run: |
          npm install
      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: |
          npm run start
